---
# For eslint 2.0.0 or later
  parserOptions:
    ecmaVersion: 6
    sourceType: "module"
  env:
    es6: true
    mocha: true
    node: true
  rules:
    block-scoped-var: 1
    curly: 2
    default-case: 2
    no-else-return: 2
    no-self-compare: 2
    no-warning-comments: 2
    no-continue: 1
    max-nested-callbacks:
      - 1
      - 3
    strict: 0
    brace-style:
      - 2
      - "1tbs"
      - allowSingleLine: false
    camelcase:
      - 2
      -
        properties: "always"
    comma-spacing:
      - 2
      -
        before: false
        after: true
    consistent-this:
      - 2
      - "self"
    func-names: 0
    indent:
      - 2
      - 2
    key-spacing:
      - 2
      -
        align: "value"
    new-cap: 2
    new-parens: 2
    no-inline-comments: 2
    no-lonely-if: 2
    no-mixed-spaces-and-tabs:
      - 2
      - "smart-tabs"
    no-multiple-empty-lines:
      - 2
      -
        max: 2
    no-nested-ternary: 2
    no-new-object: 2
    no-spaced-func: 2
    no-trailing-spaces: 2
    no-unneeded-ternary: 2
    no-extra-parens: 2
    operator-assignment:
      - 2
      - "always"
    operator-linebreak:
      - 2
      - "after"
    quotes:
      - 2
      - "single"
      - "avoid-escape"
    semi-spacing:
      - 2
      -
        before: false
        after: true
    semi:
      - 2
      - "always"
    sort-vars: 2
    keyword-spacing: 2
    space-before-blocks:
      - 2
      - "always"
    space-before-function-paren:
      - 2
      -
        anonymous: "always"
        named: "never"
    array-bracket-spacing:
      - 2
      - "never"
    space-in-parens:
      - 2
      - "never"
    space-infix-ops:
      - 2
      -
        int32Hint: false
    space-unary-ops: 2
    spaced-comment: 2
